
import './globals.css'
import 'swiper/css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providors from '@/context/Providors'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providors>
          {children}
        </Providors>
      </body>
    </html>
  )
}
